users_index:
    path: /v1/users
    defaults: { _controller: 'App\Controller\UsersController::index' }

users_show:
    path: /v1/users/{id}
    defaults: { _controller: 'App\Controller\UsersController::show' }
    requirements:
        id: \d+